### ISSUE TITLE
Metrics not returned.

### ISSUE THREAD

**Issue by gdavis33** [pyr/cyanite#104]
Cyanite is able to push metrics into cassandra but when querying in debug mode I get the following error. Paths seem to work but no metrics :(

```
curl -vvvv -X POST http://localhost:8181/paths?query=core.bidder.pops.ord.ord-bidder-x1.bidable
* About to connect() to localhost port 8181 (#0)
*   Trying ::1...
* connected
* Connected to localhost (::1) port 8181 (#0)
> POST /paths?query=core.bidder.pops.ord.ord-bidder-x1.bidable HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:8181
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Content-Type: application/json
< Transfer-Encoding: chunked
< Server: Jetty(9.2.z-SNAPSHOT)
<
* Connection #0 to host localhost left intact
[{"path":"core.bidder.pops.ord.ord-bidder-x1.bidable","depth":6,"tenant":"","leaf":true}]* Closing connection #0
```

```
curl -vvvv -X POST "http://localhost:8181/metrics?core.bidder.pops.ord.ord-bidder-x1.bidable"
* About to connect() to localhost port 8181 (#0)
*   Trying ::1...
* connected
* Connected to localhost (::1) port 8181 (#0)
> POST /metrics?core.bidder.pops.ord.ord-bidder-x1.bidable HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:8181
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 500 Server Error
< Content-Type: application/json
< Transfer-Encoding: chunked
< Server: Jetty(9.2.z-SNAPSHOT)
<
* Connection #0 to host localhost left intact
{"error":"null"}* Closing connection #0
```

From Cyanite log
```
DEBUG [2015-05-21 21:51:27,864] qtp238252453-78 - /metrics?core.bidder.pops.ord.ord-bidder-x1.bidable - io.cyanite.http - fetching paths:  nil
ERROR [2015-05-21 21:51:27,864] qtp238252453-78 - /metrics?core.bidder.pops.ord.ord-bidder-x1.bidable - io.cyanite.http - could not process request
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at io.cyanite.http$find_best_rollup$within__8661.invoke(http.clj:37)
	at clojure.core$some.invoke(core.clj:2560)
	at io.cyanite.http$find_best_rollup.invoke(http.clj:39)
	at io.cyanite.http$fn__8690.invoke(http.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at io.cyanite.http$wrap_process.invoke(http.clj:102)
	at io.cyanite.http$start$handler__8712.invoke(http.clj:123)
	at qbits.jet.server$make_handler$fn__8140.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
DEBUG [2015-05-21 21:51:27,865] qtp238252453-78 - /metrics?core.bidder.pops.ord.ord-bidder-x1.bidable - org.eclipse.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$SendCallback@780ae3ec[ITERATING][i=ResponseInfo{HTTP/1.1 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@12f9d886] generate: NEED_HEADER (null,[p=0,l=16,c=32768,r=16],false)@START
```

**Comment by gdavis33** [comment]
Incorrect url, my fault.
