### ISSUE TITLE
"/metrics/find/?query=*" fails

### ISSUE THREAD

**Issue by jippi** [pyr/cyanite#111]
I'm getting the following when trying to query cyanite 

Write seem to work just fine - unless it's an issue that the "tenant" value is an empty string :) 

I'm using ES 1.5.2 and native protocol - doesn't work with the rest protocol either :(

DEBUG [2015-07-11 13:26:31,097] qtp1567700027-89 - io.cyanite.http - got request:  {:ssl-client-cert nil, :remote-addr 80.167.165.87, :params {:query *}, :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0x40b4e787 clojure.core.async.impl.channels.ManyToManyChannel@40b4e787], :headers {accept-encoding gzip, deflate, sdch, referer http://graphite.bownty.net:8081/metrics/find/?query=*, accept-language en,en-US;q=0.8,da;q=0.6,de;q=0.4,es;q=0.2,pt;q=0.2,fr;q=0.2,it;q=0.2,sv;q=0.2, user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36, cookie conyak_guid=a91bfa73-5be264-8f9db-896234-04bf99c|CNK; grafana_sess=a8b13a71fd83d5fc; grafana_user=admin; grafana_remember=6dfa53709f1595adc77f4dfeadb759e91c1da5e31c113c66, accept */*, connection keep-alive, host graphite.bownty.net:8081}, :server-port 8081, :servlet-request #object[org.eclipse.jetty.server.Request 0x743479ce (GET /metrics/find/?query=*)@1949596110 org.eclipse.jetty.server.Request@743479ce], :content-length nil, :content-type nil, :character-encoding nil, :action :metrics, :uri /metrics/find/, :server-name graphite.bownty.net, :query-string query=*, :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0x2128fefc HttpInputOverHTTP@2128fefc], :scheme :http, :request-method :get}
DEBUG [2015-07-11 13:26:31,098] qtp1567700027-89 - io.cyanite.http - fetching paths:  nil
ERROR [2015-07-11 13:26:31,098] qtp1567700027-89 - io.cyanite.http - could not process request
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at io.cyanite.http$find_best_rollup$within__13994.invoke(http.clj:37)
	at clojure.core$some.invoke(core.clj:2568)
	at io.cyanite.http$find_best_rollup.invoke(http.clj:39)
	at io.cyanite.http$fn__14023.invoke(http.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at io.cyanite.http$wrap_process.invoke(http.clj:102)
	at io.cyanite.http$start$handler__14045.invoke(http.clj:123)
	at qbits.jet.server$make_handler$fn__13874.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:724)

**Comment by jippi** [comment]
doesn't work if i use the in-memory store either

```
DEBUG [2015-07-11 13:34:16,248] qtp456318647-67 - io.cyanite.http - got request:  {:ssl-client-cert nil, :remote-addr 80.167.165.87, :params {:query *}, :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0x2c90d810 clojure.core.async.impl.channels.ManyToManyChannel@2c90d810], :headers {accept-encoding gzip, deflate, sdch, accept-language en,en-US;q=0.8,da;q=0.6,de;q=0.4,es;q=0.2,pt;q=0.2,fr;q=0.2,it;q=0.2,sv;q=0.2, user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36, cookie conyak_guid=a91bfa73-5be264-8f9db-896234-04bf99c|CNK; grafana_sess=a8b13a71fd83d5fc; grafana_user=admin; grafana_remember=6dfa53709f1595adc77f4dfeadb759e91c1da5e31c113c66, accept text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, connection keep-alive, host graphite.bownty.net:8081, cache-control max-age=0}, :server-port 8081, :servlet-request #object[org.eclipse.jetty.server.Request 0x234bb715 (GET /metrics/find/?query=*)@592164629 org.eclipse.jetty.server.Request@234bb715], :content-length nil, :content-type nil, :character-encoding nil, :action :metrics, :uri /metrics/find/, :server-name graphite.bownty.net, :query-string query=*, :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0x3fe0d5cd HttpInputOverHTTP@3fe0d5cd], :scheme :http, :request-method :get}
DEBUG [2015-07-11 13:34:16,249] qtp456318647-67 - io.cyanite.http - fetching paths:  nil
ERROR [2015-07-11 13:34:16,249] qtp456318647-67 - io.cyanite.http - could not process request
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at io.cyanite.http$find_best_rollup$within__13994.invoke(http.clj:37)
	at clojure.core$some.invoke(core.clj:2568)
	at io.cyanite.http$find_best_rollup.invoke(http.clj:39)
	at io.cyanite.http$fn__14023.invoke(http.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at io.cyanite.http$wrap_process.invoke(http.clj:102)
	at io.cyanite.http$start$handler__14045.invoke(http.clj:123)
	at qbits.jet.server$make_handler$fn__13874.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:724)
DEBUG [2015-07-11 13:34:16,454] qtp456318647-65 - io.cyanite.http - got request:  {:ssl-client-cert nil, :remote-addr 80.167.165.87, :params {:query *}, :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0x688bb8c0 clojure.core.async.impl.channels.ManyToManyChannel@688bb8c0], :headers {accept-encoding gzip, deflate, sdch, referer http://graphite.bownty.net:8081/metrics/find/?query=*, accept-language en,en-US;q=0.8,da;q=0.6,de;q=0.4,es;q=0.2,pt;q=0.2,fr;q=0.2,it;q=0.2,sv;q=0.2, user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36, cookie conyak_guid=a91bfa73-5be264-8f9db-896234-04bf99c|CNK; grafana_sess=a8b13a71fd83d5fc; grafana_user=admin; grafana_remember=6dfa53709f1595adc77f4dfeadb759e91c1da5e31c113c66, accept */*, connection keep-alive, host graphite.bownty.net:8081}, :server-port 8081, :servlet-request #object[org.eclipse.jetty.server.Request 0x234bb715 (GET /metrics/find/?query=*)@592164629 org.eclipse.jetty.server.Request@234bb715], :content-length nil, :content-type nil, :character-encoding nil, :action :metrics, :uri /metrics/find/, :server-name graphite.bownty.net, :query-string query=*, :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0x3fe0d5cd HttpInputOverHTTP@3fe0d5cd], :scheme :http, :request-method :get}
DEBUG [2015-07-11 13:34:16,455] qtp456318647-65 - io.cyanite.http - fetching paths:  nil
ERROR [2015-07-11 13:34:16,455] qtp456318647-65 - io.cyanite.http - could not process request
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at io.cyanite.http$find_best_rollup$within__13994.invoke(http.clj:37)
	at clojure.core$some.invoke(core.clj:2568)
	at io.cyanite.http$find_best_rollup.invoke(http.clj:39)
	at io.cyanite.http$fn__14023.invoke(http.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at io.cyanite.http$wrap_process.invoke(http.clj:102)
	at io.cyanite.http$start$handler__14045.invoke(http.clj:123)
	at qbits.jet.server$make_handler$fn__13874.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:724)

```

**Comment by jippi** [comment]
Updating to Oracle JRE / JDK from the openjdk version did not do anything

-> java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by pyr** [comment]
Hi @jippi,

Can you paste the URL you're trying to retrieve, it seems to me as though you are trying to fetch paths with `/metrics/find`, whereas the correct URL is `/paths`

**Comment by jippi** [comment]
I got it fixed - I'm sorry that I can't remember what I actually did to fix it though :(

maybe I rebuild the code with oracle jdk/jre instead of openjdk
