### ISSUE TITLE
Updating to latest release o.cyanite.engine.queue could not process element on queue 2 for :writeq

### ISSUE THREAD

**Issue by petecheslock** [pyr/cyanite#113]
I had used cyanite before monitorama with great success.  But the config file I was using before doesn't seem to work anymore.  Trying to wrap my head around the config file changes.    I spun up an instance with the following config:

```
---
logging:
  level: info
  console: true
  files:
  - "/var/log/cyanite/cyanite.log"
inputs:
  host:
  - carbon
  - pickle
store:
  type: cassandra-v2
  cluster: <cassandra-db>
index:
  type: memory
api:
  port: 8080
engine:
  rules:
    default:
    - 5s:2d
```

Before I was able to configure the carbon listener and port, looks like there is now a generic TCP endpoint now - are there ways to change port/address?

When trying to send a metric with netcat
```
echo "local.random.diceroll 4 `date +%s`" | nc -q0 127.0.0.1 2002
```

Get the following
```
2015-07-29_02:36:50.94167 WARN [2015-07-29 02:36:50,941] claypoole-1-1 - io.cyanite.engine.queue nil original exception
2015-07-29_02:38:00.68103 DEBUG [2015-07-29 02:38:00,680] claypoole-1-2 - io.cyanite.engine in write callback:  #io.cyanite.engine.buckets.MetricSnapshot{:path "local.random.diceroll", :time 1438137410, :mean 4.0, :max 4.0, :min 4.0, :sum 4.0, :resolution #io.cyanite.engine.rule.Resolution{:precision 5, :period 172800}}
2015-07-29_02:38:00.68244 WARN [2015-07-29 02:38:00,682] claypoole-1-2 - io.cyanite.engine.queue could not process element on queue 2 for :writeq
2015-07-29_02:38:00.68337 java.lang.NullPointerException: null
2015-07-29_02:38:00.68343       at qbits.alia.codec.udt$encoder$fn__8491.invoke(udt.clj:116) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68348       at io.cyanite.store.cassandra$get_types$fn__9560.invoke(cassandra.clj:82) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68353       at io.cyanite.store.CassandraV2Store.insert_BANG_(store.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68358       at io.cyanite.engine.Engine$fn__9783.invoke(engine.clj:44) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68365       at io.cyanite.engine.queue$queue_engine$reify__920$future_body__921$fn__922.invoke(queue.clj:33) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68371       at io.cyanite.engine.queue$queue_engine$reify__920$future_body__921.invoke(queue.clj:32) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68377       at com.climate.claypoole.impl$binding_conveyor_fn$fn__598.invoke(impl.clj:46) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68382       at clojure.lang.AFn.applyToHelper(AFn.java:152) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68387       at clojure.lang.AFn.applyTo(AFn.java:144) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68393       at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68398       at clojure.lang.RestFn.invoke(RestFn.java:397) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68404       at clojure.lang.AFn.call(AFn.java:18) [cyanite-0.5.1-standalone.jar:na]
2015-07-29_02:38:00.68409       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
2015-07-29_02:38:00.68414       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
2015-07-29_02:38:00.68420       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
2015-07-29_02:38:00.68425       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
2015-07-29_02:38:00.68430       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
2015-07-29_02:38:00.68435       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2015-07-29_02:38:00.68597 WARN [2015-07-29 02:38:00,685] claypoole-1-2 - io.cyanite.engine.queue nil original exception
```

Probably missing a config option, but any ideas?

**Comment by petecheslock** [comment]
Also running 2.1 cassandra - and setup schema like from the doc here http://cyanite.io/concepts.html#storage-schema

**Comment by pyr** [comment]
@petecheslock I didn't update the doc to the latest schema available in doc/schema.cql, let me do that right now, sorry about this. I'll also add a more explicit error when user defined types are not found.

**Comment by pyr** [comment]
@petecheslock docs are now up to date

**Comment by petecheslock** [comment]
Awesome! Will give it a spin today.

**Comment by tjamesturner** [comment]
sounds like this issue had 2 parts:
1. the new cql schema (fixed)
2. the question about how to configure the carbon port and bind host (not addressed)

**Comment by petecheslock** [comment]
The 2nd one got fixed here https://github.com/pyr/cyanite/commit/27c18c2e2ad1c212316a831cf2739c018743b10b - with @pry's update to the config file.  
also updated the quick start yaml docs with the correct key name for `input`  https://github.com/pyr/cyanite/commit/0a3bff4787905640e866106f99f919e4f603fec2

**Comment by pyr** [comment]
@tjamesturner the example config and docs up on cyanite.io now contain appropriate documentation for 2.

**Comment by tjamesturner** [comment]
i see that now. thank you both.
