### ISSUE TITLE
Cyanite giving error when catching SIGTERM for shutdown

### ISSUE THREAD

**Issue by petecheslock** [pyr/cyanite#116]
I'm using runit to manage the cyanite service,  when stopping runit sends a SIGTERM to shutdown the process.

Seeing the following error in the logfile:
```
2015-07-29_15:41:26.54624 INFO [2015-07-29 15:41:26,546] SIGTERM handler - io.cyanite caught SIGTERM, quitting
2015-07-29_15:41:26.59241 WARN [2015-07-29 15:41:26,592] SIGTERM handler - io.cyanite uncaught exception
2015-07-29_15:41:26.59248 clojure.lang.ExceptionInfo: Error in component :api in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/stop
2015-07-29_15:41:26.59254       at clojure.core$ex_info.invoke(core.clj:4593) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59258       at com.stuartsierra.component$try_action.invoke(component.clj:118) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59263       at com.stuartsierra.component$update_system_reverse$fn__265.invoke(component.clj:150) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59267       at clojure.lang.PersistentList.reduce(PersistentList.java:117) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59272       at clojure.core$reduce.invoke(core.clj:6518) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59278       at com.stuartsierra.component$update_system_reverse.doInvoke(component.clj:146) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59284       at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59289       at com.stuartsierra.component$stop_system.invoke(component.clj:172) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59294       at com.stuartsierra.component$stop_system.invoke(component.clj:170) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59299       at io.cyanite$_main$fn__11039.invoke(cyanite.clj:77) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59304       at io.cyanite.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59309       at sun.misc.Signal$1.run(Signal.java:212) ~[na:1.8.0_45]
2015-07-29_15:41:26.59314       at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
2015-07-29_15:41:26.59320 Caused by: java.lang.NullPointerException: null
2015-07-29_15:41:26.59325       at com.climate.claypoole$shutdown.invoke(claypoole.clj:169) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59331       at io.cyanite.api.Api.stop(api.clj:116) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59336       at com.stuartsierra.component$fn__222$G__207__224.invoke(component.clj:4) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59341       at com.stuartsierra.component$fn__222$G__206__227.invoke(component.clj:4) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59346       at clojure.lang.Var.invoke(Var.java:379) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59351       at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59356       at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59362       at clojure.core$apply.invoke(core.clj:632) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59368       at com.stuartsierra.component$try_action.invoke(component.clj:116) ~[cyanite-0.5.1-standalone.jar:na]
2015-07-29_15:41:26.59372       ... 11 common frames omitted
```

This is using the latest uberjar built from current HEAD 4a95827a92bb3e7fc4569f9553db3280beba8585

**Comment by pyr** [comment]
@petecheslock last commit fixes how stop is handled in both the engine and api component and now has the expected behavior.

**Comment by petecheslock** [comment]
@pyr awesome - tested the latest build and now working as expected.

```
2015-07-29_16:00:06.86136 INFO [2015-07-29 16:00:06,860] SIGTERM handler - io.cyanite caught SIGTERM, quitting
2015-07-29_16:00:06.93187 INFO [2015-07-29 16:00:06,931] SIGTERM handler - io.cyanite all components shut down
```

**Comment by emanuelis** [comment]
Last build today gives the warning on stop.
