### ISSUE TITLE
Queue full warning

### ISSUE THREAD

**Issue by altvnk** [pyr/cyanite#121]
Hi! I'm getting some problems with cyanite after few minutes running. I'm using (graphite-stresser)[https://github.com/feangulo/graphite-stresser] to load some data. Heap is set to 512m. Here log fragment:
```
WARN [2015-08-06 13:22:23,844] nioEventLoopGroup-3-1 - io.netty.channel.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_51]
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_51]
	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__1599.add_BANG_(queue.clj:40) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine.accept_BANG_(engine.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.carbon$pipeline$fn__11523.invoke(carbon.clj:38) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.carbon.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) ~[cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite-0.5.1-standalone.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```
Does it means that cyanite fails due to slow writes into cassandra?

**Comment by AnderEnder** [comment]
+1

**Comment by AnderEnder** [comment]
Have the same error during high load with the heap 6Gb. Strange thing that  graphite carbon manage to  handle the load, while cyanite can not.

**Comment by jeffpierce** [comment]
Same thing, then falls over with an out of memory error in under 25 minutes in a low-volume staging environment.

**Comment by gmlwall** [comment]
I am also trying to P.O.C this and as soon as i send 1/8th of our prod traffic to the cyanite process i receive these errors straight away.
As mentioned  by AnderEnder, graphite-carbon can deal with this load (actually 1/4 of total load) although the caveat to this is 1/4 over carbon-c-relay, relaying to 9 carbon processes. 

Was this an issue in previous versions?

**Comment by nherson** [comment]
I am in the exact same situation as @gmlwall, this error starts right away almost immediately after cyanite starts up. Similarly, I know my standard graphite-carbon stack can handle this load.  Also, I have used the `cassandra-stress` tool and I don't believe there are issues with my cassandra setup. Has anyone been looking into this and found anything helpful?

**Comment by gmlwall** [comment]
i added the following to the config to try to give the process a bit more headroom

queues:
  default-poolsize: 24
  queue-capacity: 100000

Where default-poolsize: (no. of CPU cores on your server)

to ensure it wasn't limited by CPU usage, it lasted a bit longer before the I/O errors appeared but not tool long :(

**Comment by pyr** [comment]
@altvnk I will be starting to introduce graphite-stresser to validate further commits and resolve this issue, thanks.

**Comment by altvnk** [comment]
Sure.
I used 1024M for both -Xmx/-Xms java startup line. And as i remember i used 100 hosts, 128 times and 01 sec reporting interval. Like this: `java -jar stresser.jar 127.0.0.1 2003 100 128 10 true`

**Comment by altvnk** [comment]
Off topic: Also i've run into issues with `graphite-api`, when no grafana cannot connect and reach any metrics. I forgot details, but if you guys are going to work on these projects again i would file issues with pleasure, because i'm seriously interested in this project. Unfortunately i don't have any experience with Clojure or Java at all so i cannot contribute.

**Comment by pyr** [comment]
@altvnk Hi thanks for the feedback. the latest commit helps a lot, but doesn't solve all issues. I'm working on fixing the behavior. The issue with graphite-api is known and registered, i'm currently changing the way cyanite interacts with grafana.

Cheers!

**Comment by pyr** [comment]
Hi @altvnk,

I'm nearing the end of my work on wip/instrumented. I haven't tested the index write-path just yet, but going to cassandra I can now push with `java -jar stresser.jar 127.0.0.1 2003 100 128 2 true` (so same config, but every 2 sec) with the following config:

```yaml
engine:
  rules:
    default: [ "5s:1h" ]
api:
  port: 8080
input:
  - type: carbon
    port: 2003
index:
  type: empty
queues:
  defaults:
    ingestq:
      pool-size: 100
      queue-capacity: 2000000
    writeq:
      pool-size: 100
      queue-capacity: 2000000
store:
  cluster: 'localhost'
  keyspace: 'metric'
logging:
  level: info
  console: true
```

Note how you can now provide per-queue defaults. The trick here is to give the inputq some room to breathe.

There are now metrics exposed through JMX and /tmp/csv by default, which can help making sure the write-path and input-queues are in good shape, i'll add the ability to flush these to cassandra as well for good measure.

With this I can sucessfully run at -Xms512m -Xmx512m with no trouble. When a queue-full error occurs, it doesn't kill the daemon either. This is all in the `wip/instrumented` branch and I will modify and clean-up the commits before merging. 

Once this is done, this will leave room to update the API part to be compatible with graphite-api and the release will be around the corner.

**Comment by altvnk** [comment]
Awesome! Will take a look into it again as soon as possible.

**Comment by pyr** [comment]
@AnderEnder @gmlwall @jeffpierce @nherson 

#134 fixes this issue and should be satisfactory. Please pay attention to your index configuratin. I recommend opting for the elasticsearch index if you're in a real world scenario.

I'm leaving this issue open for now.

**Comment by altvnk** [comment]
Not sure what i'm doing wrong, but i have empty metrics in Cassandra. 
```
cqlsh> SELECT * FROM metric.metric ;

 id | time | point
----+------+-------

(0 rows)
```
Schema is created from [schema.cql](https://github.com/pyr/cyanite/blob/master/doc/schema.cql)
The most strange thing that cyanite receives metrics from python-diamond and stresser. So i'm wondering - where are they stored then? 
PS: `127.0.0.1:8080/paths` returns empty array as well.

**Comment by pyr** [comment]
Hi @altvnk,

With the above config, the index will not be provisioned since I use the "empty" indexer.
But I am seeing metrics pushed to cassandra, what is your flush period? (or better, can you paste the config that you use here?)

Cheers!

**Comment by altvnk** [comment]
Right, I changed index to memory, forgot to note this.
Anyway, I'll post my config here in a moment.

**Comment by altvnk** [comment]
Ok, i've changed only index to `memory` and carbon listen address to `0.0.0.0`. Cassandra settings are defaults. What i should verify?

**Comment by altvnk** [comment]
Sorry for confusion, tested on another cassandra cluster, metrics are writing.

Now, about original issue: performance is increased and now i'm not seeing error messages anymore.

**Comment by pyr** [comment]
Hi @altvnk,

Thanks for your help in testing this. I will close this ticket for now and focus on finishing the direct grafana integration.

Sounds as if the release is getting really close now :-)
