### ISSUE TITLE
WARN io.cyanite.engine.queue queue is full, no metrics

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#135]
I've just changed y index type from memory to elasticsearch. Here's my configuration:

```yml
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
inputs:
  - type: "carbon"
  - type: "pickle"
store:
  type: "cassandra-v2"
  cluster: "192.168.0.126"
index:
  type: "elasticsearch"
  url: "http://192.168.0.1:9201/cyanite"
api:
  port: 8080
engine:
  rules:
    default:
      - "5s:30d"
```

I do have metrics in cassandra as everything worked with "memory" index. Metrics names appeared in ES and I get there names at ```http://cyanite:8080/paths?query=*```. But all the datasets return empty, for example:

```diff
+ target=groupByNode(stats.timers.starman.response.time.*.sum%2C%204%2C%20'sum')&from=-6h&until=now&format=json&maxDataPoints=480
- 127.000.000.001.08888-127.000.000.001.39976: []
```

This message appears in logs repeatedly:

```
WARN [2015-10-14 17:37:25,124] pool-8-thread-2 - io.cyanite.engine.queue queue is full
```

And here's some log lines from the start:

```
INFO [2015-10-14 19:19:56,391] main - io.cyanite.engine starting engine
INFO [2015-10-14 19:19:56,498] main - org.eclipse.jetty.server.Server jetty-9.3.z-SNAPSHOT
INFO [2015-10-14 19:19:56,503] main - org.eclipse.jetty.server.ServerConnector Started ServerConnector@287ae90c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO [2015-10-14 19:19:56,505] main - org.eclipse.jetty.server.Server Started @5097ms
WARN [2015-10-14 19:20:02,353] nioEventLoopGroup-2-2 - io.netty.channel.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
clojure.lang.ExceptionInfo: invalid carbon line: NaN metric
        at clojure.core$ex_info.invoke(core.clj:4593) ~[cyanite.jar:na]
        at io.cyanite.input.carbon$parse_line.invoke(carbon.clj:22) ~[cyanite.jar:na]
        at io.cyanite.input.carbon$pipeline$fn__9853.invoke(carbon.clj:38) ~[cyanite.jar:na]
        at io.cyanite.input.carbon.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [cyanite.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
WARN [2015-10-14 19:20:11,969] nioEventLoopGroup-2-3 - io.cyanite.engine.queue queue is full
```

**Comment by pyr** [comment]
Hi @hryamzik,

You will need to work with the queue settings for both `ingestq` and `writeq`, I will bump the default value before finishing up the release.

I suggest you take inspiration from https://github.com/pyr/cyanite/issues/121#issuecomment-145795928

**Comment by pyr** [comment]
Closing this for now, since #121 takes care of it.
