### ISSUE TITLE
Trouble connecting to cassandra with latest cyanite release

### ISSUE THREAD

**Issue by lrsmith** [pyr/cyanite#138]
I'm having trouble starting up cyanite on:

jdk1.8.0_25-1.8.0_25-fcs.x86_64
Cassandra 2.1
cyanite-0.5.1
Centos 6.6

I see a warning then an error. In my store stanza I specify username, password, keyspace and cluster. I downloaded the latest cyanite, from master.  I've also verified I can connect to the cassandra cluster from the host using the username and password, to the cluster. So it is not a network or auth issue.

I've dug around a bit and tried different things but so far I get the same behavior. If I remove the username/password I get an authentication error. I was/am able to connect using an older version of cyanite. I did drop and recreate the keyspace and verified it is up to date. I also tried adding type: 'cassandra-v2' to the store section and that did not resolve the issue.

Any help or suggestion appreciated.

store:
  cluster: '1.2.9.3'
  keyspace: 'metric'
  username: foo
  password: bar

java -jar /tmp/cyanite/target/cyanite-0.5.1-standalone.jar -f /etc/cyanite.yaml

......
WARN [2015-10-16 17:28:40,017] main - io.cyanite uncaught exception
clojure.lang.ExceptionInfo: Error in component :store in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/start
	at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$try_action.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system$fn__317.invoke(component.cljc:139) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6536) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$update_system.doInvoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite-0.5.1-standalone.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.main(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /1.2.9.3:9042 (com.datastax.driver.core.ConnectionException: [/1.2.9.3:9042] Unexpected error during transport initialization (java.lang.NullPointerException)))

Debug did show a little more 

DEBUG [2015-10-16 17:21:47,092] cluster1-nio-worker-0 - com.datastax.driver.core.Connection Connection[/1.2.9.3:9042-1, inFlight=0, closed=false] Connection opened successfully
DEBUG [2015-10-16 17:21:47,116] cluster1-nio-worker-0 - com.datastax.shaded.netty.util.Recycler -Dio.netty.recycler.maxCapacity.default: 262144
DEBUG [2015-10-16 17:21:47,153] cluster1-nio-worker-0 - com.datastax.driver.core.Host.STATES Defuncting Connection[/1.2.9.3:9042-1, inFlight=0, closed=false] because: [/1.2.9.3:9042] Unexpected error during transport initialization (java.lang.NullPointerException)

**Comment by pyr** [comment]
Hi @lrsmith,

Can you paste your indented config here ?

**Comment by lrsmith** [comment]
logging:
  level: debug
  console: true
  files:
    - "/tmp/cyanite.log"

inputs:
  - type: carbon
    port: 2003
  - type: pickle
    port: 2004


api:
  port: 8080

engine:
  rules:
    default: [ "5s:1h" ]

store:
  cluster: '1.2.9.3'
  keyspace: 'metric'
  username: 'my_user'
  password: 'my_password'

**Comment by jippi** [comment]
@lrsmith can you paste it again with ``` around it, so the indent is preserved

**Comment by lrsmith** [comment]
Fixed it above. thanks.

**Comment by pyr** [comment]
@lrsmith The error is due to an unreachable cluster. The error is a bit buried in the stack-trace:

```
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /1.2.9.3:9042 (com.datastax.driver.core.ConnectionException: [/1.2.9.3:9042] Unexpected error during transport initialization (java.lang.NullPointerException)))
```

**Comment by lrsmith** [comment]
@pyr I've verified with the cqlsh command, on the host in question, that I can actually connect to the cluster and the metric database, with the user and password from the config. I'll double check but it only seem to by the cyanite code that is having the problem.

**Comment by pyr** [comment]
@lrsmith I was handing out an incorrect map to the underlying cassandra driver. Sorry about this!

**Comment by lrsmith** [comment]
pyr. Thank you everything looks much better now. Thanks
