### ISSUE TITLE
No method in multimethod 'build-index' for dispatch value: :elasticsearch

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#140]
Cyanite with ES based index fails to start with the following message:

```
WARN [2015-10-19 20:05:06,819] main - io.cyanite uncaught exception
java.lang.IllegalArgumentException: No method in multimethod 'build-index' for dispatch value: :elasticsearch
        at clojure.lang.MultiFn.getFn(MultiFn.java:156) ~[cyanite.jar:na]
        at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[cyanite.jar:na]
        at clojure.core$update.invokeStatic(core.clj:5952) ~[cyanite.jar:na]
        at clojure.core$update.invoke(core.clj) ~[cyanite.jar:na]
        at io.cyanite$config__GT_system.invokeStatic(cyanite.clj:74) ~[cyanite.jar:na]
        at io.cyanite$config__GT_system.invoke(cyanite.clj) ~[cyanite.jar:na]
        at io.cyanite$_main.invokeStatic(cyanite.clj:90) ~[cyanite.jar:na]
        at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite.jar:na]
        at io.cyanite.main(Unknown Source) ~[cyanite.jar:na]
```

And it seems like a new issue as the same config worked for me a week ago in a similar environment. Manual index creation doesn't help.

**Comment by pyr** [comment]
Hi @hryamzik,

As I was mentioning in #137 the ES index is gone for now since it is now possible to index metrics in Cassandra directly. I'll probably make the the index come back in a short-while. Right now there are two possible options for indexing `agent` (in memory) and `cassandra`

**Comment by hryamzik** [comment]
Wow, that's good news indeed! I'll give ```cassandra``` option a try, thanks!
