### ISSUE TITLE
Problems with indexes on ElasticSearch

### ISSUE THREAD

**Issue by emanuelis** [pyr/cyanite#142]
Hi. I installed latest Cyanite from git. It works with memory indexes but not with ElasticSearch.

If I configure only:
```
index: elasticsearch
```
Cyanite ignores it and uses memory.

If I configure:
```
index:
  use: "io.cyanite.es_path/es-rest"
  index: "cyanite_paths" #defaults to "cyanite_paths"
  url: "http://localhost:9200"
  chan_size: 1000 # defaults to 1000
  batch_size: 1000 # defaults to 1000
```
Cyanite ignores it and uses memory.

If I configure:
```
index: elasticsearch
  url: "http://localhost:9200/cyanite_paths"
```
Cyanite dies on startup with:
```
12:05:37.807 [main] WARN  io.cyanite - uncaught exception
org.yaml.snakeyaml.scanner.ScannerException: null; mapping values are not allowed here
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:764) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:324) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:191) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:213) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:602) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:186) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:157) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:177) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:197) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:138) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:100) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:83) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:114) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.Loader.load(Loader.java:51) ~[cyanite.jar:na]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:152) ~[cyanite.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[cyanite.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[cyanite.jar:na]
	at clj_yaml.core$parse_string.invokeStatic(core.clj:78) ~[cyanite.jar:na]
	at clj_yaml.core$parse_string.invoke(core.clj) ~[cyanite.jar:na]
	at io.cyanite.config$load_path.invokeStatic(config.clj:20) ~[cyanite.jar:na]
	at io.cyanite.config$load_path.invoke(config.clj) ~[cyanite.jar:na]
	at io.cyanite$config__GT_system.invokeStatic(cyanite.clj:58) ~[cyanite.jar:na]
	at io.cyanite$config__GT_system.invoke(cyanite.clj) ~[cyanite.jar:na]
	at io.cyanite$_main.invokeStatic(cyanite.clj:90) ~[cyanite.jar:na]
	at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite.jar:na]
	at io.cyanite.main(Unknown Source) ~[cyanite.jar:na]
```

Is this a bug or my misconfiguration? How to configure ElasticSearch properly? Do I need to create index in ES by hand? If yes, then how?

**Comment by pyr** [comment]
Hi @emanuelis,

As I was mentioning in #137 the ES index is gone for now since it is now possible to index metrics in Cassandra directly. I'll probably make the the index come back in a short-while. Right now there are two possible options for indexing agent (in memory) and cassandra

**Comment by chjohnst** [comment]
What's the performance overhead of indexing in Cassandra in comparison to
ES?

**Comment by pyr** [comment]
Hi @chjohnst,

It still passes the 200k metric/s test with a 512m fixed heap.
The indexing technique is described in #137.

**Comment by chjohnst** [comment]
Going to try your latest code drop on some new keyspaces I'm putting
together, will report some feedback in the coming days on issues I find.
My Cassandra and cyanite deployment is getting pretty big!

**Comment by pyr** [comment]
Hi @chjohnst,

Thanks a lot! If your deployment is big you will need to adjust your queue-sizes to avoid the dreaded "Queue Full" messages. The description here will help: https://github.com/pyr/cyanite/issues/121#issuecomment-145795928

FWIW, I have several reports of cyanite now correctly working with graphite-api. The remaining work needed for a release to make it is https://github.com/pyr/cyanite/issues/136. If you're already using graphite-api or graphite-web as a vessel to get to Cyanite data, there is nothing barring you from trying it out.

I'll watch for your issues, cheers!
