### ISSUE TITLE
invalid carbon line: NaN metric

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#144]
This issue was already mentioned in #135 but turned out to be a separate one. Here's the log:

```
WARN [2015-10-21 17:32:17,778] nioEventLoopGroup-2-2 - io.netty.channel.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
clojure.lang.ExceptionInfo: invalid carbon line: NaN metric
        at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite.jar:na]
        at clojure.core$ex_info.invoke(core.clj) ~[cyanite.jar:na]
        at io.cyanite.input.carbon$parse_line.invokeStatic(carbon.clj:22) ~[cyanite.jar:na]
        at io.cyanite.input.carbon$parse_line.invoke(carbon.clj) ~[cyanite.jar:na]
        at io.cyanite.input.carbon$pipeline$fn__8793.invoke(carbon.clj:38) ~[cyanite.jar:na]
        at io.cyanite.input.carbon.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[cyanite.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[cyanite.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [cyanite.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

It would be nice to see the problematic metric in log.

**Comment by jshook** [comment]
+1 seeing it as well. I'd like this to be caught and logged as a single line with the offending input.

**Comment by jshook** [comment]
PR #151 includes a simple change to show the paths in this exception

**Comment by pyr** [comment]
#151 has been merged.
