### ISSUE TITLE
Stable Release milestones

### ISSUE THREAD

**Issue by jshook** [pyr/cyanite#146]
PYR,

I'm trying to integrate a newer version of cyanite into some other testing work. It looks like the code base is in a state of flux at the moment. 

I tried the current master, but there are are stack traces starting with:
clojure.lang.ExceptionInfo: Error in component :index in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/start
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
which appears to be related to C* pool or client management [ for indexes in C* ]

Can you recommend a commit or branch that I should use that works with the usual graphite api and grafana integrations?

### UPDATE

After some troubleshooting, I was able to move forward. Still, some idea on the current status or stable releases would be very helpful.

**Comment by jshook** [comment]
Just for additional info, I've included the stack trace below:

clojure.lang.ExceptionInfo: Error in component :index in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/start
        at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system$fn__319.invoke(component.cljc:139) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6536) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system.doInvoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.main(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
        at qbits.alia.cluster_options$fn__8031.invokeStatic(cluster_options.clj:35) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$fn__8031.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.MultiFn.invoke(MultiFn.java:238) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_$fn__8174.invoke(cluster_options.clj:285) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6734.invokeStatic(protocols.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6734.invoke(protocols.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6676$G__6671__6689.invoke(protocols.clj:13) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6537) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_.invokeStatic(cluster_options.clj:284) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia$cluster.invokeStatic(alia.clj:184) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia$cluster.invoke(alia.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra$session_BANG_.invokeStatic(cassandra.clj:47) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra$session_BANG_.invoke(cassandra.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra.CassandraIndex.start(cassandra.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$fn__268$G__262__270.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$fn__268$G__261__273.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.Var.invoke(Var.java:379) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:647) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$apply.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117) ~[cyanite-0.5.1-standalone.jar:na]
        ... 16 common frames omitted

**Comment by brutasse** [comment]
@jshook Hi, @pyr is away for a couple of days… Right now master is definitely the latest and greatest & works fine with graphite-api and grafana. I think pyr wants to have direct grafana integration completely done (#136) before making a new release.

**Comment by jshook** [comment]
Thank you for the update, @brutasse 
I will continue working with master.

**Comment by pyr** [comment]
Hi @jshook,

@brutasse is right about the status. #136 + stability and perf tests are the remaining items before doing the first real cyanite release. I hope to finish up soon.
