### ISSUE TITLE
Problems with queues/GC/Agent/connections/?

### ISSUE THREAD

**Issue by emanuelis** [pyr/cyanite#149]
Hi, today I upgraded Cyanite to the "latest and gratest" ((c) @brutasse). And after ~5 hours of normal running it stopped collecting data. Log doesn't say much to me.

Many such warnings:
```
WARN [2015-10-22 18:18:55,241] pool-9-thread-7845 - io.cyanite.engine.queue could not process element on queue 7844 for :writeq
clojure.lang.ExceptionInfo: Query execution failed
	at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite.jar:na]
	at clojure.core$ex_info.invoke(core.clj) ~[cyanite.jar:na]
	at qbits.alia$ex__GT_ex_info.invokeStatic(alia.clj:210) ~[cyanite.jar:na]
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj) ~[cyanite.jar:na]
	at qbits.alia$ex__GT_ex_info.invokeStatic(alia.clj:216) ~[cyanite.jar:na]
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj) ~[cyanite.jar:na]
	at qbits.alia$execute.invokeStatic(alia.clj:370) ~[cyanite.jar:na]
	at qbits.alia$execute.invoke(alia.clj) ~[cyanite.jar:na]
	at io.cyanite.store.cassandra$runq_BANG_.invokeStatic(cassandra.clj:53) ~[cyanite.jar:na]
	at io.cyanite.store.cassandra$runq_BANG_.invoke(cassandra.clj) ~[cyanite.jar:na]
	at io.cyanite.store.CassandraV2Store.insert_BANG_(store.clj:41) ~[cyanite.jar:na]
	at io.cyanite.engine.Engine$fn__8687.invoke(engine.clj:56) ~[cyanite.jar:na]
	at io.cyanite.engine.queue.BlockingMemoryQueue$fn__833$fn__834.invoke(queue.clj:59) ~[cyanite.jar:na]
	at io.cyanite.engine.queue.BlockingMemoryQueue$fn__833.invoke(queue.clj:58) [cyanite.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) [cyanite.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.DriverException: Timeout while trying to acquire available connection (you may want to increase the driver number of per-host connections)))
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:217) ~[cyanite.jar:na]
	at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:44) ~[cyanite.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.sendRequest(RequestHandler.java:276) ~[cyanite.jar:na]
	at com.datastax.driver.core.RequestHandler.startNewExecution(RequestHandler.java:117) ~[cyanite.jar:na]
	at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:93) ~[cyanite.jar:na]
	at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:127) ~[cyanite.jar:na]
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52) ~[cyanite.jar:na]
	at qbits.alia$execute.invokeStatic(alia.clj:366) ~[cyanite.jar:na]
	... 13 common frames omitted
```
And later many:
```
WARN [2015-10-22 21:36:16,917] pool-9-thread-8127 - io.cyanite.engine.queue nil original exception
WARN [2015-10-22 21:36:16,917] pool-9-thread-1633 - io.cyanite.engine.queue nil original exception
WARN [2015-10-22 21:36:16,917] pool-9-thread-5409 - io.cyanite.engine.queue could not process element on queue 5408 for :writeq
java.lang.RuntimeException: Agent is failed, needs restart
	at clojure.lang.Util.runtimeException(Util.java:225) ~[cyanite.jar:na]
	at clojure.lang.Agent.dispatch(Agent.java:238) ~[cyanite.jar:na]
	at clojure.core$send_via.invokeStatic(core.clj:2010) ~[cyanite.jar:na]
	at clojure.core$send_via.doInvoke(core.clj) ~[cyanite.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:146) ~[cyanite.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:651) ~[cyanite.jar:na]
	at clojure.core$send_off.invokeStatic(core.clj:2032) ~[cyanite.jar:na]
	at clojure.core$send_off.doInvoke(core.clj) ~[cyanite.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:566) ~[cyanite.jar:na]
	at io.cyanite.index.AgentIndex.push_segment_BANG_(index.clj:20) ~[cyanite.jar:na]
	at io.cyanite.index$register_BANG_.invokeStatic(index.clj:78) ~[cyanite.jar:na]
	at io.cyanite.index$register_BANG_.invoke(index.clj) ~[cyanite.jar:na]
	at io.cyanite.engine.Engine$fn__8687.invoke(engine.clj:55) ~[cyanite.jar:na]
	at io.cyanite.engine.queue.BlockingMemoryQueue$fn__833$fn__834.invoke(queue.clj:59) ~[cyanite.jar:na]
	at io.cyanite.engine.queue.BlockingMemoryQueue$fn__833.invoke(queue.clj:58) [cyanite.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) [cyanite.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

My config is:
```
engine:
  rules:
    "test.*": [ "1s:1m", "5s:5d" ]
    "live.*": [ "1s:1d" ]
    default: [ "60s:60d" ]
api:
  port: 8080
input:
  - type: carbon
    port: 2003
    host: 0.0.0.0
  - type: pickle
    port: 2004
    host: 0.0.0.0
index:
  type: agent
store:
  cluster: 'localhost'
  keyspace: 'metric'
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
  overrides:
    io.cyanite: "debug"

queues:
  defaults:
    ingestq:
      pool-size: 10000
      queue-capacity: 2000000
    writeq:
      pool-size: 10000
      queue-capacity: 2000000
```

What can I do to make Cyanite more stable?

**Comment by pyr** [comment]
Hi @emanuelis,

If you have many paths, I suggest you switch to the `cassandra` type of index, not the in-memory one. The first stack-trace you posted is due to unreachable cassandra nodes, see the "Caused by" line of the logs:

> Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.DriverException: Timeout while trying to acquire available connection (you may want to increase the driver number of per-host connections)))

**Comment by emanuelis** [comment]
Cassandra indexes were too slow to work with Grafana.
Actually at the moment I had to suspend the deployment of Cyanite due to numerous bugs and switch to other product :(

**Comment by pyr** [comment]
@emanuelis sorry to hear that. I'm trying to get a first stable release out soon.
