### ISSUE TITLE
com.datastax.driver.core.exceptions.WriteTimeoutException

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#152]
Just found this in logs. Would be nice to catch these exceptions...

```
pool-16-thread-20 - io.cyanite.engine.queue could not process element on queue 19 for :writeq
clojure.lang.ExceptionInfo: Query execution failed
        at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite.jar:na]
        at clojure.core$ex_info.invoke(core.clj) ~[cyanite.jar:na]
        at qbits.alia$ex__GT_ex_info.invokeStatic(alia.clj:210) ~[cyanite.jar:na]
        at qbits.alia$ex__GT_ex_info.invoke(alia.clj) ~[cyanite.jar:na]
        at qbits.alia$ex__GT_ex_info.invokeStatic(alia.clj:216) ~[cyanite.jar:na]
        at qbits.alia$ex__GT_ex_info.invoke(alia.clj) ~[cyanite.jar:na]
        at qbits.alia$execute.invokeStatic(alia.clj:370) ~[cyanite.jar:na]
        at qbits.alia$execute.invoke(alia.clj) ~[cyanite.jar:na]
        at io.cyanite.index.cassandra$runq_BANG_.invokeStatic(cassandra.clj:67) ~[cyanite.jar:na]
        at io.cyanite.index.cassandra$runq_BANG_.invoke(cassandra.clj) ~[cyanite.jar:na]
        at io.cyanite.index.cassandra.CassandraIndex.push_segment_BANG_(cassandra.clj:91) ~[cyanite.jar:na]
        at io.cyanite.index$register_BANG_.invokeStatic(index.clj:78) ~[cyanite.jar:na]
        at io.cyanite.index$register_BANG_.invoke(index.clj) ~[cyanite.jar:na]
        at io.cyanite.engine.Engine$fn__8691.invoke(engine.clj:55) ~[cyanite.jar:na]
        at io.cyanite.engine.queue.BlockingMemoryQueue$fn__837$fn__838.invoke(queue.clj:59) ~[cyanite.jar:na]
        at io.cyanite.engine.queue.BlockingMemoryQueue$fn__837.invoke(queue.clj:58) [cyanite.jar:na]
        at clojure.lang.AFn.run(AFn.java:22) [cyanite.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency ONE (2 replica were required but only 1 acknowledged the write)
        at com.datastax.driver.core.exceptions.WriteTimeoutException.copy(WriteTimeoutException.java:100) ~[cyanite.jar:na]
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:98) ~[cyanite.jar:na]
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:149) ~[cyanite.jar:na]
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:183) ~[cyanite.jar:na]
        at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:44) ~[cyanite.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:748) ~[cyanite.jar:na]
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:587) ~[cyanite.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) ~[cyanite.jar:na]
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[cyanite.jar:na]
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) ~[cyanite.jar:na]
        ... 1 common frames omitted
```

**Comment by pyr** [comment]
Hi @hryamzik,

There's not much cyanite can do if cassandra is unavailable. If you're willing to sacrifice consistency, you can tune down the CL to ONE (see the write-consistency setting in the documentation).

> Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency ONE (2 replica were required but only 1 acknowledged the write)

**Comment by hryamzik** [comment]
I would expect cyanite to catch this and put a single line error in log, not a full stack...
