### ISSUE TITLE
Cassandra index does not work

### ISSUE THREAD

**Issue by spynode** [pyr/cyanite#155]
When using Cassandra as index, with keyspace metric and schema provided in https://github.com/pyr/cyanite/blob/master/doc/schema.cql, Cyanite throws exception:

```
WARN [2015-10-23 16:24:29,742] main - io.cyanite uncaught exception
clojure.lang.ExceptionInfo: Error in component :index in system clojure.lang.PersistentArrayMap calling #'com.stuartsierra.component/start
        at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system$fn__315.invoke(component.cljc:139) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6536) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$update_system.doInvoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$start_system.invoke(component.cljc) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite$_main.doInvoke(cyanite.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.main(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
        at qbits.alia.cluster_options$fn__8027.invokeStatic(cluster_options.clj:35) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$fn__8027.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.MultiFn.invoke(MultiFn.java:238) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_$fn__8170.invoke(cluster_options.clj:285) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6734.invokeStatic(protocols.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6734.invoke(protocols.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core.protocols$fn__6676$G__6671__6689.invoke(protocols.clj:13) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6537) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$reduce.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_.invokeStatic(cluster_options.clj:284) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia.cluster_options$set_cluster_options_BANG_.invoke(cluster_options.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia$cluster.invokeStatic(alia.clj:184) ~[cyanite-0.5.1-standalone.jar:na]
        at qbits.alia$cluster.invoke(alia.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra$session_BANG_.invokeStatic(cassandra.clj:47) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra$session_BANG_.invoke(cassandra.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at io.cyanite.index.cassandra.CassandraIndex.start(cassandra.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$fn__264$G__258__266.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$fn__264$G__257__269.invoke(component.cljc:5) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.Var.invoke(Var.java:379) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$apply.invokeStatic(core.clj:647) ~[cyanite-0.5.1-standalone.jar:na]
        at clojure.core$apply.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
        at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117) ~[cyanite-0.5.1-standalone.jar:na]
        ... 16 common frames omitted
```

Is this schema problem and if so, where optimal schema for index keyspace can be found?

**Comment by aww-yiss** [comment]
I also encountered this error, however it was due to a misconfiguration I made in the cyanite.yaml for the index. Here is an exampled of a structure that is working for me today for 0.5.1:

``` yaml
index:
  type: cassandra
  options:
    cluster: 127.0.0.1
```

I think this is a fairly new feature and the documentation needs to be updated to make this a bit more apparent.

If this  doesn't correct the issue can you also post your cyanite.yaml config?

**Comment by pyr** [comment]
Yep, this is a configuration error.
