### ISSUE TITLE
WARN - io.cyanite.input.pickle cannot deserialize pickle

### ISSUE THREAD

**Issue by aww-yiss** [pyr/cyanite#158]
Hello, I've got cyanite accepting plaintext metrics and insert them into cassandra, then query them back out using the graphite-api and the graphite-cyanite finder. Works well so far :)

I'm trying to implement a side by side comparison of cyanite with an existing graphite setup, and have added the cyanite collector as a destination for the existing carbon-relay, and using relay-rules.conf to send data to the existing graphite nodes, and to the cyanite node.

The cyanite instance is not able to accept the pickled metrics from the carbon-relay as seen below, however the relay is still forwarding to graphite and is working well there.

```
WARN [2015-11-04 14:39:33,439] nioEventLoopGroup-2-2 - io.cyanite.input.pickle cannot deserialize pickle
clojure.lang.ExceptionInfo: invalid pickle data
	at clojure.core$ex_info.invokeStatic(core.clj:4610) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$ex_info.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at pickler.parser$fn__8903.invokeStatic(parser.clj:101) ~[cyanite-0.5.1-standalone.jar:na]
	at pickler.parser$fn__8903.invoke(parser.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:233) ~[cyanite-0.5.1-standalone.jar:na]
	at pickler.parser$raw__GT_ast$fn__8905.invoke(parser.clj:112) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Cons.next(Cons.java:39) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RT.next(RT.java:688) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$next__4334.invokeStatic(core.clj:64) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$nthnext.invokeStatic(core.clj:3055) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$nthnext.invoke(core.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at pickler.parser$ast__GT_metrics.invokeStatic(parser.clj:127) ~[cyanite-0.5.1-standalone.jar:na]
	at pickler.parser$ast__GT_metrics.invoke(parser.clj) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.pickle$pickle_lines.invokeStatic(pickle.clj:16) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.pickle$pickle_lines.invoke(pickle.clj) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.pickle$pipeline$fn__8941.invoke(pickle.clj:29) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.pickle.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
```

And below is my `cyanite.yaml`

```
index:
  type: cassandra
  options:
    cluster: ["cass1.redacteddomain.com", "cass2.redacteddomain.com", "cass3.redacteddomain.com" ]
    keyspace: metric
logging:
  level: info
  console: false
  files:
    - '/var/log/cyanite/cyanite.log'
input:
  - type: 'carbon'
    host: '0.0.0.0'
    port: 2003
  - type: 'pickle'
    host: '0.0.0.0'
    port: 2004
store:
  cluster: ["cass1.redacteddomain.com", "cass2.redacteddomain.com", "cass3.redacteddomain.com" ]
  keyspace: 'metric'
api:
  host: '10.80.0.90'
  port: 8080
engine:
  rules:
    default: [ "1m:14d", "5m:30d", "10m:90d" ]
```

**Comment by aww-yiss** [comment]
Still not a lot of luck getting this working, though I have spent some time with the carbon-c-relay project, and have had some good results there. 

What version of pickle is supported? The graphite instance i'm using for testing is rather old (0.9.10) and using python 2.6 libraries.

**Comment by genericgithubuser** [comment]
We see the same exception.  The stats are forwarded from graphite 0.9.9 relay.  Looks like it'll use pickle protocol v2.  Any known incompatibilities or workarounds for this one?

**Comment by pyr** [comment]
@aww-yiss with the carbon-c-relay project, you're succesfully able to input pickle metrics and output to the text carbon format in front of cyanite?

**Comment by pyr** [comment]
As per #176, we have decided to hold off on pickle for now.

**Comment by aww-yiss** [comment]
@pyr regarding carbon-c-relay, It *only* supports the plaintext protocol, and we decided on moving away from using the pickle formatted metrics everywhere, and just receiving and relaying metrics in the plaintext format. 

The rational being that all our collectors have been configured to push metrics in plaintext format anyways, so the only thing which was talking pickle were remote carbon-relay processes, and they weren't handling the load well to begin with, so they've been swapped out in favor of carbon-c-relay, which was a significant improvement for throughput.
