### ISSUE TITLE
Exception on loading data (missing method?)

### ISSUE THREAD

**Issue by carlf** [pyr/cyanite#189]
We are trying to test out cyanite. We are hitting this error:

```
WARN [2016-02-12 01:30:54,064] pool-1-thread-1 - io.cyanite uncaught exception
java.lang.RuntimeException: java.lang.IllegalArgumentException: No implementation of method: :metric-matches? of protocol: #'io.cyanite.engine.rule/MetricMatcher found for class: clojure.lang.MapEntry
	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.dsl.ExceptionHandlerWrapper.handleEventException(ExceptionHandlerWrapper.java:18) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:148) ~[cyanite-0.5.1-standalone.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: No implementation of method: :metric-matches? of protocol: #'io.cyanite.engine.rule/MetricMatcher found for class: clojure.lang.MapEntry
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$fn__720$G__715__727.invoke(rule.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$__GT_exec_plan$fn__755.invoke(rule.clj:66) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$some.invokeStatic(core.clj:2592) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$some.invoke(core.clj:2583) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$__GT_exec_plan.invokeStatic(rule.clj:66) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$__GT_exec_plan.invoke(rule.clj:64) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$make_resolutions.invokeStatic(engine.clj:61) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$make_resolutions.invoke(engine.clj:59) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fetch_resolutions.invokeStatic(engine.clj:68) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fetch_resolutions.invoke(engine.clj:64) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine.ingest_BANG_(engine.clj:95) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fn__3970$G__3966__3973.invoke(engine.clj:18) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fn__3970$G__3965__3977.invoke(engine.clj:18) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$partial$fn__4759.invoke(core.clj:2515) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue.DisruptorQueue$fn__3675.invoke(queue.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$event_handler$reify__3655.onEvent(queue.clj:49) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) ~[cyanite-0.5.1-standalone.jar:na]
	... 3 common frames omitted
```

We are using Cassandra 3.0.3 and current master with this config:

```
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite.log"
input:
  - type: "carbon"
store:
  cluster:
    - 'host1'
    - 'host2'
    - 'host3'
  keyspace: 'metric'
index:
  type: cassandra
  options:
    cluster:
      - 'host1'
      - 'host2'
      - 'host3'
api:
  port: 8080
engine:
  rules:
    default: [ "10s:30d" ]
```

**Comment by ifesdjeen** [comment]
This was a result of recent refactoring and is already addressed in #185.

We are working very hard to make the release available within the next several weeks. We are in the process of stabilizing and removing performance bottlenecks at the moment.
