### ISSUE TITLE
API is not starting up

### ISSUE THREAD

**Issue by pawellesniewski** [pyr/cyanite#250]
Hi there,
api of cyanite 0.5.1 version is not starting up in my case.

Before running cyanite (only cassandra 3.9 running on docker):
```
:~# free -m
              total        used        free      shared  buff/cache   available
Mem:          32174        8677       22965          10         532       23123
Swap:             0           0           0
```

starting logs:
```
INFO [2016-10-07 08:08:02,420] main - io.cyanite installing signal handlers
INFO [2016-10-07 08:08:02,427] main - io.cyanite ready to start the system
DEBUG [2016-10-07 08:08:02,541] main - com.datastax.driver.core.SystemProperties com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
DEBUG [2016-10-07 08:08:02,544] main - com.datastax.driver.core.SystemProperties com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 8
DEBUG [2016-10-07 08:08:02,552] main - com.datastax.driver.core.SystemProperties com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
DEBUG [2016-10-07 08:08:02,674] main - com.datastax.driver.core.Cluster Starting new cluster with contact points [/172.17.0.2:9042]
DEBUG [2016-10-07 08:08:02,772] main - com.datastax.shaded.netty.util.internal.logging.InternalLoggerFactory Using SLF4J as the default logging framework
DEBUG [2016-10-07 08:08:02,809] main - com.datastax.shaded.netty.util.internal.PlatformDependent0 java.nio.Buffer.address: unavailable
DEBUG [2016-10-07 08:08:02,811] main - com.datastax.shaded.netty.util.internal.PlatformDependent Java version: 8
DEBUG [2016-10-07 08:08:02,812] main - com.datastax.shaded.netty.util.internal.PlatformDependent -Dio.netty.noUnsafe: false
DEBUG [2016-10-07 08:08:02,812] main - com.datastax.shaded.netty.util.internal.PlatformDependent sun.misc.Unsafe: unavailable
DEBUG [2016-10-07 08:08:02,813] main - com.datastax.shaded.netty.util.internal.PlatformDependent maxDirectMemory: 19327352832 bytes (maybe)
DEBUG [2016-10-07 08:08:02,814] main - com.datastax.shaded.netty.util.internal.PlatformDependent -Dio.netty.noJavassist: false
DEBUG [2016-10-07 08:08:02,819] main - com.datastax.shaded.netty.util.internal.PlatformDependent Javassist: unavailable
DEBUG [2016-10-07 08:08:02,819] main - com.datastax.shaded.netty.util.internal.PlatformDependent You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
DEBUG [2016-10-07 08:08:02,819] main - com.datastax.shaded.netty.util.internal.PlatformDependent -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
DEBUG [2016-10-07 08:08:02,820] main - com.datastax.shaded.netty.util.internal.PlatformDependent -Dio.netty.bitMode: 64 (sun.arch.data.model)
DEBUG [2016-10-07 08:08:02,820] main - com.datastax.shaded.netty.util.internal.PlatformDependent -Dio.netty.noPreferDirect: true
INFO [2016-10-07 08:08:02,821] main - com.datastax.shaded.netty.util.internal.PlatformDependent Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
DEBUG [2016-10-07 08:08:02,836] main - com.datastax.driver.core.SystemProperties com.datastax.driver.FORCE_NIO is undefined, using default value false
INFO [2016-10-07 08:08:02,838] main - com.datastax.driver.core.NettyUtil Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
DEBUG [2016-10-07 08:08:02,844] main - com.datastax.shaded.netty.channel.MultithreadEventLoopGroup -Dio.netty.eventLoopThreads: 16
DEBUG [2016-10-07 08:08:02,858] main - com.datastax.shaded.netty.channel.nio.NioEventLoop -Dio.netty.noKeySetOptimization: false
DEBUG [2016-10-07 08:08:02,859] main - com.datastax.shaded.netty.channel.nio.NioEventLoop -Dio.netty.selectorAutoRebuildThreshold: 512
DEBUG [2016-10-07 08:08:02,893] main - com.datastax.shaded.netty.util.ResourceLeakDetector -Dcom.datastax.shaded.netty.leakDetection.level: simple
DEBUG [2016-10-07 08:08:02,894] main - com.datastax.shaded.netty.util.ResourceLeakDetector -Dcom.datastax.shaded.netty.leakDetection.maxRecords: 4
DEBUG [2016-10-07 08:08:03,115] main - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] preparing to open 1 new connections, total = 1
DEBUG [2016-10-07 08:08:03,120] main - com.datastax.driver.core.SystemProperties com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
DEBUG [2016-10-07 08:08:03,166] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.numHeapArenas: 16
DEBUG [2016-10-07 08:08:03,167] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.numDirectArenas: 16
DEBUG [2016-10-07 08:08:03,167] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.pageSize: 8192
DEBUG [2016-10-07 08:08:03,167] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.maxOrder: 11
DEBUG [2016-10-07 08:08:03,168] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.chunkSize: 16777216
DEBUG [2016-10-07 08:08:03,168] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.tinyCacheSize: 512
DEBUG [2016-10-07 08:08:03,168] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.smallCacheSize: 256
DEBUG [2016-10-07 08:08:03,168] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.normalCacheSize: 64
DEBUG [2016-10-07 08:08:03,169] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.maxCachedBufferCapacity: 32768
DEBUG [2016-10-07 08:08:03,169] main - com.datastax.shaded.netty.buffer.PooledByteBufAllocator -Dio.netty.allocator.cacheTrimInterval: 8192
DEBUG [2016-10-07 08:08:05,246] main - com.datastax.shaded.netty.util.internal.ThreadLocalRandom -Dio.netty.initialSeedUniquifier: 0x5d2cff1e1e9c7477 (took 2032 ms)
DEBUG [2016-10-07 08:08:05,275] main - com.datastax.shaded.netty.buffer.ByteBufUtil -Dio.netty.allocator.type: unpooled
DEBUG [2016-10-07 08:08:05,275] main - com.datastax.shaded.netty.buffer.ByteBufUtil -Dio.netty.threadLocalDirectBufferSize: 65536
DEBUG [2016-10-07 08:08:05,276] main - com.datastax.shaded.netty.buffer.ByteBufUtil -Dio.netty.maxThreadLocalCharBufferSize: 16384
DEBUG [2016-10-07 08:08:05,311] cluster1-nio-worker-0 - com.datastax.driver.core.Connection Connection[/172.17.0.2:9042-1, inFlight=0, closed=false] Connection established, initializing transport
DEBUG [2016-10-07 08:08:05,342] cluster1-nio-worker-0 - com.datastax.shaded.netty.util.Recycler -Dio.netty.recycler.maxCapacity.default: 262144
DEBUG [2016-10-07 08:08:05,364] cluster1-nio-worker-0 - com.datastax.shaded.netty.buffer.AbstractByteBuf -Dcom.datastax.shaded.netty.buffer.bytebuf.checkAccessible: true
DEBUG [2016-10-07 08:08:05,435] cluster1-nio-worker-0 - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] Connection[/172.17.0.2:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
DEBUG [2016-10-07 08:08:05,440] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing node list and token map
DEBUG [2016-10-07 08:08:05,485] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing schema
DEBUG [2016-10-07 08:08:05,634] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing node list and token map
DEBUG [2016-10-07 08:08:05,676] main - com.datastax.driver.core.Host.STATES [Control connection] established to /172.17.0.2:9042
INFO [2016-10-07 08:08:05,676] main - com.datastax.driver.core.policies.DCAwareRoundRobinPolicy Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO [2016-10-07 08:08:05,677] main - com.datastax.driver.core.Cluster New Cassandra host /172.17.0.2:9042 added
DEBUG [2016-10-07 08:08:05,682] main - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] preparing to open 1 new connections, total = 2
DEBUG [2016-10-07 08:08:05,693] cluster1-nio-worker-1 - com.datastax.driver.core.Connection Connection[/172.17.0.2:9042-2, inFlight=0, closed=false] Connection established, initializing transport
DEBUG [2016-10-07 08:08:05,719] cluster1-nio-worker-1 - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] Connection[/172.17.0.2:9042-2, inFlight=0, closed=false] Transport initialized, connection ready
DEBUG [2016-10-07 08:08:05,724] cluster1-nio-worker-1 - com.datastax.driver.core.HostConnectionPool Created connection pool to host /172.17.0.2:9042 (1 connections needed, 1 successfully opened)
DEBUG [2016-10-07 08:08:05,725] cluster1-nio-worker-1 - com.datastax.driver.core.Session Added connection pool for /172.17.0.2:9042
INFO [2016-10-07 08:08:05,776] main - io.cyanite.engine starting engine
DEBUG [2016-10-07 08:08:05,784] main - com.datastax.driver.core.Cluster Starting new cluster with contact points [/172.17.0.2:9042]
DEBUG [2016-10-07 08:08:05,796] main - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] preparing to open 1 new connections, total = 1
DEBUG [2016-10-07 08:08:05,807] cluster2-nio-worker-0 - com.datastax.driver.core.Connection Connection[/172.17.0.2:9042-1, inFlight=0, closed=false] Connection established, initializing transport
DEBUG [2016-10-07 08:08:05,848] cluster2-nio-worker-0 - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] Connection[/172.17.0.2:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
DEBUG [2016-10-07 08:08:05,855] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing node list and token map
DEBUG [2016-10-07 08:08:05,883] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing schema
DEBUG [2016-10-07 08:08:06,020] main - com.datastax.driver.core.ControlConnection [Control connection] Refreshing node list and token map
DEBUG [2016-10-07 08:08:06,045] main - com.datastax.driver.core.Host.STATES [Control connection] established to /172.17.0.2:9042
INFO [2016-10-07 08:08:06,045] main - com.datastax.driver.core.policies.DCAwareRoundRobinPolicy Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO [2016-10-07 08:08:06,045] main - com.datastax.driver.core.Cluster New Cassandra host /172.17.0.2:9042 added
DEBUG [2016-10-07 08:08:06,046] main - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] preparing to open 1 new connections, total = 2
DEBUG [2016-10-07 08:08:06,059] cluster2-nio-worker-1 - com.datastax.driver.core.Connection Connection[/172.17.0.2:9042-2, inFlight=0, closed=false] Connection established, initializing transport
DEBUG [2016-10-07 08:08:06,099] cluster2-nio-worker-1 - com.datastax.driver.core.Host.STATES [/172.17.0.2:9042] Connection[/172.17.0.2:9042-2, inFlight=0, closed=false] Transport initialized, connection ready
DEBUG [2016-10-07 08:08:06,102] cluster2-nio-worker-1 - com.datastax.driver.core.HostConnectionPool Created connection pool to host /172.17.0.2:9042 (1 connections needed, 1 successfully opened)
DEBUG [2016-10-07 08:08:06,103] cluster2-nio-worker-1 - com.datastax.driver.core.Session Added connection pool for /172.17.0.2:9042
INFO [2016-10-07 08:08:06,129] main - io.cyanite.engine.writer starting writer engine
DEBUG [2016-10-07 08:08:06,162] main - io.netty.channel.MultithreadEventLoopGroup -Dio.netty.eventLoopThreads: 16
DEBUG [2016-10-07 08:08:06,176] main - io.netty.channel.nio.NioEventLoop -Dio.netty.noKeySetOptimization: false
DEBUG [2016-10-07 08:08:06,176] main - io.netty.channel.nio.NioEventLoop -Dio.netty.selectorAutoRebuildThreshold: 512
DEBUG [2016-10-07 08:08:07,248] main - io.netty.util.internal.ThreadLocalRandom -Dio.netty.initialSeedUniquifier: 0x9ae1c5f4366851dd (took 1060 ms)
DEBUG [2016-10-07 08:08:07,297] main - io.netty.buffer.ByteBufUtil -Dio.netty.allocator.type: unpooled
DEBUG [2016-10-07 08:08:07,297] main - io.netty.buffer.ByteBufUtil -Dio.netty.threadLocalDirectBufferSize: 65536
DEBUG [2016-10-07 08:08:07,305] main - io.netty.buffer.ByteBufUtil -Dio.netty.maxThreadLocalCharBufferSize: 16384
DEBUG [2016-10-07 08:08:07,307] main - io.netty.util.NetUtil Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
DEBUG [2016-10-07 08:08:07,308] main - io.netty.util.NetUtil /proc/sys/net/core/somaxconn: 128
DEBUG [2016-10-07 08:08:07,334] main - io.netty.util.internal.NativeLibraryLoader -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
DEBUG [2016-10-07 08:08:07,334] main - io.netty.util.internal.NativeLibraryLoader -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
INFO [2016-10-07 08:08:11,136] pool-16-thread-1 - io.cyanite.engine.writer starting snapshot.
INFO [2016-10-07 08:08:11,138] pool-16-thread-2 - io.cyanite.engine.writer starting snapshot.
WARN [2016-10-07 08:08:12,321] main - io.cyanite uncaught exception
clojure.lang.ExceptionInfo: Error in component :api in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start
	at clojure.core$ex_info.invokeStatic(core.clj:4617) ~[cyanite.jar:na]
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:116) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system$fn__330.invoke(component.cljc:135) ~[cyanite.jar:na]
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6544) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:129) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:129) ~[cyanite.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc:155) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc:155) ~[cyanite.jar:na]
	at clojure.lang.Atom.swap(Atom.java:37) ~[cyanite.jar:na]
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2260) ~[cyanite.jar:na]
	at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite.jar:na]
	at io.cyanite$_main.doInvoke(cyanite.clj:81) ~[cyanite.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite.jar:na]
	at io.cyanite.main(Unknown Source) ~[cyanite.jar:na]
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68) ~[cyanite.jar:na]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:49) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invokeStatic(http.clj:143) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invoke(http.clj:137) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invokeStatic(http.clj:140) ~[cyanite.jar:na]
	at io.cyanite.api.Api.start(api.clj:161) ~[cyanite.jar:na]
	at com.stuartsierra.component$fn__279$G__273__281.invoke(component.cljc:5) ~[cyanite.jar:na]
	at com.stuartsierra.component$fn__279$G__272__284.invoke(component.cljc:5) ~[cyanite.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) ~[cyanite.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite.jar:na]
	at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:648) ~[cyanite.jar:na]
	... 17 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.netty.util.internal.PlatformDependent0.allocateMemory(PlatformDependent0.java:330) ~[cyanite.jar:na]
	at io.netty.util.internal.PlatformDependent.allocateMemory(PlatformDependent.java:210) ~[cyanite.jar:na]
	at io.netty.channel.epoll.IovArray.<init>(IovArray.java:64) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:57) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:76) ~[cyanite.jar:na]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64) ~[cyanite.jar:na]
	... 31 common frames omitted
INFO [2016-10-07 08:08:16,135] pool-16-thread-3 - io.cyanite.engine.writer starting snapshot.
INFO [2016-10-07 08:08:16,138] cyanite-snapshot - io.cyanite.engine.writer starting snapshot.
INFO [2016-10-07 08:08:21,136] pool-16-thread-4 - io.cyanite.engine.writer starting snapshot.
```

most interesting part of starting logs:
```
clojure.lang.ExceptionInfo: Error in component :api in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start
	at clojure.core$ex_info.invokeStatic(core.clj:4617) ~[cyanite.jar:na]
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:116) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system$fn__330.invoke(component.cljc:135) ~[cyanite.jar:na]
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114) ~[cyanite.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6544) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:129) ~[cyanite.jar:na]
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:129) ~[cyanite.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:445) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc:155) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161) ~[cyanite.jar:na]
	at com.stuartsierra.component$start_system.invoke(component.cljc:155) ~[cyanite.jar:na]
	at clojure.lang.Atom.swap(Atom.java:37) ~[cyanite.jar:na]
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2260) ~[cyanite.jar:na]
	at io.cyanite$_main.invokeStatic(cyanite.clj:103) ~[cyanite.jar:na]
	at io.cyanite$_main.doInvoke(cyanite.clj:81) ~[cyanite.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[cyanite.jar:na]
	at io.cyanite.main(Unknown Source) ~[cyanite.jar:na]
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68) ~[cyanite.jar:na]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:49) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invokeStatic(http.clj:143) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invoke(http.clj:137) ~[cyanite.jar:na]
	at io.cyanite.http$run_server.invokeStatic(http.clj:140) ~[cyanite.jar:na]
	at io.cyanite.api.Api.start(api.clj:161) ~[cyanite.jar:na]
	at com.stuartsierra.component$fn__279$G__273__281.invoke(component.cljc:5) ~[cyanite.jar:na]
	at com.stuartsierra.component$fn__279$G__272__284.invoke(component.cljc:5) ~[cyanite.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) ~[cyanite.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[cyanite.jar:na]
	at clojure.lang.Var.applyTo(Var.java:700) ~[cyanite.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:648) ~[cyanite.jar:na]
	... 17 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.netty.util.internal.PlatformDependent0.allocateMemory(PlatformDependent0.java:330) ~[cyanite.jar:na]
	at io.netty.util.internal.PlatformDependent.allocateMemory(PlatformDependent.java:210) ~[cyanite.jar:na]
	at io.netty.channel.epoll.IovArray.<init>(IovArray.java:64) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:57) ~[cyanite.jar:na]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:76) ~[cyanite.jar:na]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64) ~[cyanite.jar:na]
	... 31 common frames omitted
```

ingest port (2003:tcp) looks good:
```
:~# netstat -tapn | grep -i listen | grep java
tcp6       0      0 :::2003                 :::*                    LISTEN      29752/java
```

even with a lot of memory:
```
EXTRA_JAVA_OPTS="-Xmx18g -Xms8g"
```

Configuration file:
```
engine:
  rules:
    "web.*\\.cpu": [ "5s:1h", "30s:1d" ]
    default: [ "5s:1h" ]
api:
  host: 0.0.0.0
  port: 8888
  disabled: false
input:
  - type: carbon
    host: 0.0.0.0
    port: 2003
index:
  type: cassandra
  cluster:
    - 172.17.0.2
  keyspace: 'metric'

drift:
  type: agent
store:
  cluster:
    - 172.17.0.2
  keyspace: 'metric'

logging:
  level: debug
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
```

please help.

**Comment by pawellesniewski** [comment]
The problem was with my java version.

**Comment by ifesdjeen** [comment]
\o/ did you run 1.7 or 1.9?..

Thanks for posting your findings here!
