### ISSUE TITLE
Getting Unknown signal :HUP

### ISSUE THREAD

**Issue by priyavivek1** [pyr/cyanite#267]
i ak trying running cyanite on windows and getting following error. Is  there any workaround for same.

java.lang.IllegalArgumentException: Unknown signal: HUP
        at sun.misc.Signal.<init>(Unknown Source)
        at signal.handler$__GT_signal.invokeStatic(handler.clj:7)
        at signal.handler$on_signal.invokeStatic(handler.clj:25)
        at io.cyanite$_main.invokeStatic(cyanite.clj:91)
        at io.cyanite$_main.doInvoke(cyanite.clj:81)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at io.cyanite.main(Unknown Source)

**Comment by ifesdjeen** [comment]
When do you get it? On startup?

**Comment by priyavivek1** [comment]
@ifesdjeen : Yes, when i run cyanite standalone .jar, i get it. i tried on windows as well as MAC OS

**Comment by ifesdjeen** [comment]
It does work for me on mac os x, so I can not reproduce it.
As regards windows, unfortunately I do not have an access to Windows dev machines.

**Comment by ifesdjeen** [comment]
Ok, looks like this is Windows-specific: Windows doesn't have a HUP signal equivalent. So I'm not sure how you have gotten this on Mac OS X.
