### ISSUE TITLE
Support for multiple elasticsearch nodes in index

### ISSUE THREAD

**Issue by jpotter** [pyr/cyanite#66]
Is there a way to configure cyanite to use more than one node for elasticsearch?

It looks like the yaml file only supports passing in one node for elasticsearch when I follow the yaml convention. That is, this works:

index:
  use: "io.cyanite.es_path/es-native"
  index: "cyanite_stats_paths" #defaults to "cyanite_paths"
  host: "192.168.1.103"

But this gives the below exception:

index:
  use: "io.cyanite.es_path/es-native"
  index: "cyanite_stats_paths" #defaults to "cyanite_paths"
  host:
    - "192.168.1.103"
    - "192.168.1.102"

(Additionally, it would be nice to be able to pass the port number in as part of the host, so one can do "localhost:8300, localhost:9300" to test failover on a local machine.)

Thanks,
Jeff

 Exception in thread "main" java.lang.ClassCastException: clojure.lang.LazySeq cannot be cast to java.lang.String
	at clojurewerkz.elastisch.native.conversion$__GT_socket_transport_address.invokePrim(conversion.clj:174)
	at clojurewerkz.elastisch.native$connect.invoke(native.clj:250)
	at io.cyanite.es_path$es_native.invoke(es_path.clj:198) 	at clojure.lang.Var.invoke(Var.java:379)
	at io.cyanite.config$instantiate.invoke(config.clj:94) 	at io.cyanite.config$get_instance.invoke(config.clj:102)
 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
 	at clojure.lang.AFn.applyTo(AFn.java:144)
 	at clojure.core$apply.invoke(core.clj:628)
 	at clojure.core$update_in.doInvoke(core.clj:5853)
 	at clojure.lang.RestFn.invoke(RestFn.java:467)
 	at io.cyanite.config$init.invoke(config.clj:129)
 	at io.cyanite$_main.doInvoke(cyanite.clj:31)
 	at clojure.lang.RestFn.applyTo(RestFn.java:137) 	at io.cyanite.main(Unknown Source)

**Comment by pyr** [comment]
Hi @jpotter,

I will stop providing a native ES connector, going further. This means that going to multiple ES nodes should only involve load balancing them.
