### ISSUE TITLE
Cannot use Value Lists in metric paths

### ISSUE THREAD

**Issue by WrathOfChris** [pyr/cyanite#70]
Having issues rendering metrics that use a _Value List_ "ie: something.{x,y}" as the metric path (http://graphite-api.readthedocs.org/en/latest/api.html#paths-and-wildcards)

Setup is (graphite-api + graphite-cyanite) to cyanite

Simple test: `http://localhost/render?target=%7Btest%2Ctest2%7D`

```
ERROR [2014-10-23 21:05:24,068] qtp847087923-77 - io.cyanite.http - could not process request
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
^{test,test2}.*$
^
```

Full stack trace:
```
DEBUG [2014-10-23 21:05:24,065] qtp847087923-77 - io.cyanite.http - got request:  {:ssl-client-cert nil, :remote-addr 172.20.15.44, :params {:query {test,test2}}, :headers {x-forwarded-port 80, accept */*, connection keep-alive, user-agent python-requests/2.4.3 CPython/2.7.3 Linux/3.2.0-70-virtual, x-forwarded-for XXX.XXX.XXX.XXX, x-forwarded-proto http, accept-encoding gzip, deflate, host graphite-cyanite.XXXXXXXX.com}, :server-port 80, :content-length nil, :content-type nil, :character-encoding nil, :action :paths, :uri /paths, :server-name graphite-cyanite.XXXXXXXX.com, :query-string query=%7Btest%2Ctest2%7D, :body #<HttpInputOverHTTP HttpInputOverHTTP@615c027c>, :scheme :http, :request-method :get}
DEBUG [2014-10-23 21:05:24,066] qtp847087923-77 - io.cyanite.http - query now:  {test,test2}
ERROR [2014-10-23 21:05:24,068] qtp847087923-77 - io.cyanite.http - could not process request
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
^{test,test2}.*$
^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.closure(Pattern.java:3104)
	at java.util.regex.Pattern.sequence(Pattern.java:2101)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at clojure.core$re_pattern.invoke(core.clj:4602)
	at io.cyanite.path$path_elem_re.invoke(path.clj:18)
	at clojure.core$map$fn__4345.invoke(core.clj:2612)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.lang.RT.countFrom(RT.java:582)
	at clojure.lang.RT.count(RT.java:575)
	at io.cyanite.path$memory_pathstore$reify__5940.prefixes(path.clj:85)
	at io.cyanite.http$fn__12887.invoke(http.clj:72)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at io.cyanite.http$wrap_process.invoke(http.clj:102)
	at io.cyanite.http$start$handler__12915.invoke(http.clj:123)
	at qbits.jet.server$make_handler$fn__11572.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hitthefrei** [comment]
@WrathOfChris 
Hi, do find a way to resolve this issue?

**Comment by WrathOfChris** [comment]
@hitthefrei no, only got as far as identifying it.  I'm only using elasticsearch, so can't speak to the internal path store.

cyanite passes the full query string directly to the elasticsearch `regexp` search parameter, only mutating it in `build-es-filter` to replace '.' and '*' with correctly escaped chars for regex.

Would definitely need to escape '{' and '}', but may need to do more to match regexp format correctly for ES: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html

This is what gets passed in the ES query from the original query "servers.{testing,test}":
(I removed http escaping for clarity):

```
{
  "regexp": {
    "path": "servers\.{testing,test}",
    "_cache": true
  }
}
```

**Comment by hitthefrei** [comment]
Thank you, @WrathOfChris !
I resolve this issue with changing in cyanite/src/io/cyanite/es_path.clj

I change  `p (str/replace (str/replace path "." "\\.") "*" ".*")` to p `(str/replace (str/replace (str/replace (str/replace (str/replace path "," "|") "}" ")") "{" "(") "." "\\.") "*" ".*")` , and it's works!

**Comment by WrathOfChris** [comment]
Submitted a modified version of your fix as a PR: https://github.com/pyr/cyanite/pull/94

**Comment by pyr** [comment]
Hi this is now correctly processed in #80. So sorry for the wait :-(
