### ISSUE TITLE
updated-core: broken carbon transport

### ISSUE THREAD

**Issue by luxifr** [pyr/cyanite#84]
Hi,

tried updated-core today, but I can't get it to work. Upon start it throws lots and lots of io.netty.channel.ChannelPipelineException like so:

```
WARN [2014-12-08 14:24:35,645] nioEventLoopGroup-2-3 - io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x9497119c, /192.168.1.100:40769 => /192.168.1.1
00:2003]
io.netty.channel.ChannelPipelineException: io.netty.handler.codec.LineBasedFrameDecoder is not a @Sharable handler, so can't be added or removed multiple times.
        at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:461)
        at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:138)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:131)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:258)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:245)
        at io.cyanite.transport.tcp$server_bootstrap$fn__8987.invoke(tcp.clj:60)
        at io.cyanite.transport.tcp.proxy$io.netty.channel.ChannelInitializer$ff19274a.initChannel(Unknown Source)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRegistered(DefaultChannelHandlerContext.java:166)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRegistered(DefaultChannelHandlerContext.java:152)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:730)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
```

this is the config I use:
```yaml
transports:
  - host: "192.168.1.100"
    use: "io.cyanite.transport.carbon/carbon-transport"
    port: 2003
    readtimeout: 30
http:
  host: "0.0.0.0"
  port: 8001
logging:
  level: "info"
  console: true
  files:
    - "/var/log/cyanite.log"
index:
  use: "io.cyanite.index.atom/atom-index"
store:
  use: "io.cyanite.store.cassandra/cassandra-store"
  cluster: "localhost"
  keyspace: "metric"
precisions:
  - period: 604800
    rollup: 10
  - period: 2419200
    rollup: 300
  - period: 7257600
    rollup: 900
  - period: 29030400
    rollup: 3600
```

**Comment by MichaelHierweck** [comment]
There seems to be a bug related to the code that bootstraps tcp servers in tcp.clj. It seems only a single LineBasedFrameDecoder is created and shared across the tcp listeners. Instead every listener requires an instance on its own.

**Comment by pyr** [comment]
Hi,

#80 has now a fixed carbon input. sorry for the wait.
