### ISSUE TITLE
Grafana compatibility issue with metric names

### ISSUE THREAD

**Issue by jshook** [pyr/cyanite#89]
I attempted to use this with grafana, but there are issues in the metric name discovery:
(configured with no elastic search for cyanite in this instance)

java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:404)
        at java.lang.Long.parseLong(Long.java:483)
        at io.cyanite.http$find_best_rollup$within__8633.invoke(http.clj:37)
        at clojure.core$some.invoke(core.clj:2560)
        at io.cyanite.http$find_best_rollup.invoke(http.clj:39)
        at io.cyanite.http$fn__8662.invoke(http.clj:77)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at io.cyanite.http$wrap_process.invoke(http.clj:102)
        at io.cyanite.http$start$handler__8684.invoke(http.clj:123)
        at qbits.jet.server$make_handler$fn__8112.invoke(server.clj:70)
        at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jshook** [comment]
Not an issue.
