### ISSUE TITLE
HoltWintersAberration: list index out of range

### ISSUE THREAD

**Issue by resnostyle** [pyr/cyanite#98]
The holtWintersAberration function isnt displaying anything on graphite-web. The logs display the following stack trace. 
This is also using a version .10.x using a alternate storage method, cyanite with cassandra backend.

Here's the call I'm making for example: curl 'http://localhost/render/?from=-7days&until=-1minutes&uniq=1426001228492&format=json&target=holtWintersAberration(statsd.processing_time)'
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 111, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 9, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 38, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 38, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 23, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 42, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 2293, in holtWintersAberration
    lowerBand = confidenceBands[0]
IndexError: list index out of range
```

**Comment by pyr** [comment]
I'll integrate this in the tests before merging #80.
